server:
  port: 8080

spring:
  application:
    name: secure-password-generator

  datasource:
    url: jdbc:h2:mem:pwgendb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password: ""

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        format_sql: false

  h2:
    console:
      enabled: false   # Never enable in production

app:
  encryption:
    key: ""            # Leave empty for ephemeral dev key
  breach-check:
    enabled: true      # Set false to skip real HIBP calls

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

logging:
  level:
    root: INFO
    com.securepwgen: DEBUG
    org.springframework.security: WARN
